[[machines]]
name = "machine1"
username = "user1"
key = "key1"

  [[machines.hosts]]
  ip = "192.168.1.1"
  port = "8080"
  iface = "eth0"

  [[machines.hosts]]
  ip = "192.168.1.2"
  port = "8081"
  iface = "eth1"

[[machines]]
name = "machine2"
username = "user2"
key = "key2"

  [[machines.hosts]]
  ip = "192.168.2.1"
  port = "8080"
  iface = "eth0"

  [[machines.hosts]]
  ip = "192.168.2.2"
  port = "8081"
  iface = "eth1"